class AppLanguage {
  static String code = 'en';

  static void setCode(String newCode) {
    code = newCode;
  }

  static String t(String key) {
    final map = code == 'fr' ? _fr : _en;
    return map[key] ?? key;
  }

  static const Map<String, String> _en = {
    // Home
    'home_hello_prefix': 'Hello',
    'home_events_this_week': 'You have 3 events this week',
    'home_upcoming': 'Upcoming events',
    'home_top_picks': 'Top Picks',
    'home_filter_all': 'All',
    'home_filter_recent': 'Recent',
    'home_filter_closest': 'Closest',
    'home_search_hint': 'Search...',
    'home_view_all': 'View all',
    
    // Login
    'login_app_name': 'Eventify',
    'login_app_tagline': 'Discover amazing events',
    'login_welcome': 'Welcome Back',
    'login_signin_desc': 'Sign in to continue',
    'login_email_hint': 'Email',
    'login_password_hint': 'Password',
    'login_remember_me': 'Remember me',
    'login_forgot_password': 'Forgot Password?',
    'login_signin_button': 'Sign In',
    'login_or': 'or',
    'login_google_signin': 'Continue with Google',
    'login_no_account': "Don't have an account? ",
    'login_signup_link': 'Sign Up',
    
    // Sign Up
    'signup_title': 'Create Account',
    'signup_desc': 'Sign up to discover amazing events',
    'signup_fullname_hint': 'Full Name',
    'signup_confirm_password': 'Confirm Password',
    'signup_agree_terms': 'I agree to the ',
    'signup_terms': 'Terms & Conditions',
    'signup_and': ' and ',
    'signup_privacy': 'Privacy Policy',
    'signup_button': 'Sign Up',
    'signup_have_account': 'Already have an account? ',
    'signup_login_link': 'Login',
    
    // Profile
    'profile_title': 'Profile',
    'profile_personal_info': 'Personal Information',
    'profile_activity': 'Activity',
    'profile_manage_account': 'Manage my account',
    'profile_app_privacy': 'App & Privacy',
    'profile_my_privacy_data': 'My Privacy & data',
    'profile_logout': 'Logout',
    'profile_change_picture': 'Profile picture change feature',
    'profile_logout_title': 'Logout',
    'profile_logout_confirm': 'Are you sure you want to logout?',
    'profile_cancel': 'Cancel',
    'profile_logout_success': 'Logged out successfully',
    'profile_edit': 'Edit',
    'profile_save': 'Save',
    'profile_username': 'Username',
    'profile_email': 'Email',
    'profile_mobile': 'Mobile Number',
    'profile_score': 'Score',
    'profile_attended': 'Attended',
    'profile_created': 'Created',
    'profile_favorites': 'Favorites',
    'profile_ad_prefs': 'Ad Preferences',
    'profile_session_mgmt': 'Session Management',
    'profile_browser_settings': 'Browser Settings',
    
    // Favorites
    'favorites_title': 'Favorites',
    'favorites_event': 'Event',
    'favorites_events': 'Events',
    
    // Settings
    'settings_title': 'Settings',
    'settings_notifications': 'Notifications',
    'settings_push_notifications': 'Push Notifications',
    'settings_push_desc': 'Receive notifications about upcoming events',
    'settings_email_notifications': 'Email Notifications',
    'settings_email_desc': 'Receive event updates via email',
    'settings_language_section': 'Language',
    'settings_app_language': 'App Language',
    'settings_event_preferences': 'Event Preferences',
    'settings_categories': 'Categories',
    'settings_preferred_locations': 'Preferred Locations',
    'settings_free_events_only': 'Free Events Only',
    'settings_free_events_desc': 'Show only free events',
    'settings_general': 'General',
    'settings_privacy_policy': 'Privacy Policy',
    'settings_terms_of_service': 'Terms of Service',
    'settings_about': 'About',
    'settings_help_support': 'Help & Support',
    'settings_select_language': 'Select Language',
    'settings_about_eventify': 'About Eventify',
    'settings_version': 'Version 1.0.0',
    'settings_about_desc': 'Eventify is your go-to app for discovering and managing events.',
    'settings_copyright': '© 2025 Eventify. All rights reserved.',
    'settings_close': 'Close',
    'settings_select_categories': 'Select Categories',
    'settings_done': 'Done',
    'settings_cancel': 'Cancel',
    'settings_select_locations': 'Select Locations',
    'settings_add': 'Add',
  };

  static const Map<String, String> _fr = {
    // Home
    'home_hello_prefix': 'Bonjour',
    'home_events_this_week': 'Vous avez 3 événements cette semaine',
    'home_upcoming': 'Événements à venir',
    'home_top_picks': 'Sélections',
    'home_filter_all': 'Tous',
    'home_filter_recent': 'Récents',
    'home_filter_closest': 'Les plus proches',
    'home_search_hint': 'Rechercher...',
    'home_view_all': 'Tout voir',
    
    // Login
    'login_app_name': 'Eventify',
    'login_app_tagline': 'Découvrez des événements incroyables',
    'login_welcome': 'Bon retour',
    'login_signin_desc': 'Connectez-vous pour continuer',
    'login_email_hint': 'E-mail',
    'login_password_hint': 'Mot de passe',
    'login_remember_me': 'Se souvenir',
    'login_forgot_password': 'Mot de passe oublié?',
    'login_signin_button': 'Connexion',
    'login_or': 'ou',
    'login_google_signin': 'Continuer avec Google',
    'login_no_account': "Pas de compte? ",
    'login_signup_link': "S'inscrire",
    
    // Sign Up
    'signup_title': 'Créer un compte',
    'signup_desc': 'Inscrivez-vous pour découvrir',
    'signup_fullname_hint': 'Nom complet',
    'signup_confirm_password': 'Confirmer',
    'signup_agree_terms': "J'accepte les ",
    'signup_terms': 'Conditions',
    'signup_and': ' et la ',
    'signup_privacy': 'Confidentialité',
    'signup_button': "S'inscrire",
    'signup_have_account': 'Déjà un compte? ',
    'signup_login_link': 'Connexion',
    
    // Profile
    'profile_title': 'Profil',
    'profile_personal_info': 'Informations personnelles',
    'profile_activity': 'Activité',
    'profile_manage_account': 'Gérer mon compte',
    'profile_app_privacy': 'App & Confidentialité',
    'profile_my_privacy_data': 'Confidentialité et données',
    'profile_logout': 'Déconnexion',
    'profile_change_picture': 'Changer la photo de profil',
    'profile_logout_title': 'Déconnexion',
    'profile_logout_confirm': 'Voulez-vous vraiment vous déconnecter?',
    'profile_cancel': 'Annuler',
    'profile_logout_success': 'Déconnexion réussie',
    'profile_edit': 'Modifier',
    'profile_save': 'Enregistrer',
    'profile_username': "Nom d'utilisateur",
    'profile_email': 'E-mail',
    'profile_mobile': 'Mobile',
    'profile_score': 'Score',
    'profile_attended': 'Assistés',
    'profile_created': 'Créés',
    'profile_favorites': 'Favoris',
    'profile_ad_prefs': 'Publicités',
    'profile_session_mgmt': 'Sessions',
    'profile_browser_settings': 'Navigateur',
    
    // Favorites
    'favorites_title': 'Favoris',
    'favorites_event': 'Événement',
    'favorites_events': 'Événements',
    
    // Settings
    'settings_title': 'Paramètres',
    'settings_notifications': 'Notifications',
    'settings_push_notifications': 'Notifications push',
    'settings_push_desc': 'Recevoir des notifications',
    'settings_email_notifications': 'Notifications e-mail',
    'settings_email_desc': 'Mises à jour par e-mail',
    'settings_language_section': 'Langue',
    'settings_app_language': "Langue de l'app",
    'settings_event_preferences': 'Préférences',
    'settings_categories': 'Catégories',
    'settings_preferred_locations': 'Lieux préférés',
    'settings_free_events_only': 'Gratuits uniquement',
    'settings_free_events_desc': 'Événements gratuits',
    'settings_general': 'Général',
    'settings_privacy_policy': 'Confidentialité',
    'settings_terms_of_service': "Conditions d'utilisation",
    'settings_about': 'À propos',
    'settings_help_support': 'Aide',
    'settings_select_language': 'Sélectionner la langue',
    'settings_about_eventify': 'À propos',
    'settings_version': 'Version 1.0.0',
    'settings_about_desc': 'Eventify pour découvrir et gérer des événements.',
    'settings_copyright': '© 2025 Eventify. Tous droits réservés.',
    'settings_close': 'Fermer',
    'settings_select_categories': 'Sélectionner',
    'settings_done': 'Terminé',
    'settings_cancel': 'Annuler',
    'settings_select_locations': 'Sélectionner des lieux',
    'settings_add': 'Ajouter',
  };
}


