# Generated by Django 5.2.8 on 2026-01-09 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventApp", "0004_remove_event_photo_url_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                blank=True, default="dall.png", upload_to="photos/"
            ),
        ),
        migrations.CreateModel(
            name="Repost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reposts",
                        to="EventApp.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reposts",
                        to="EventApp.user",
                    ),
                ),
            ],
            options={
                "db_table": "reposts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="reposts_user_id_ba7781_idx"),
                    models.Index(fields=["event"], name="reposts_event_i_72b68c_idx"),
                    models.Index(
                        fields=["-created_at"], name="reposts_created_fa23e5_idx"
                    ),
                ],
                "unique_together": {("user", "event")},
            },
        ),
    ]
